Complex changes
ACRIOS-Systems/pyUBX pull request #1
Opened 2023-04-26 08:07 UTC by Hadatko

-- different approach to serialize data and serialize also repeated data.
 -- generate allowed numbers
-- generate masks and offsets

2023-05-03 12:27 UTC, qcabrol commented on lang/cpp/src/Ubx.hpp
> +namespace ubx
missing comment headers

2023-05-03 12:27 UTC, qcabrol commented on lang/cpp/src/Ubx.cpp
> +        writeByte(getDataSize() & 0x00ff, buf, index);
little endian order

2023-05-05 10:25 UTC, qcabrol requested changes

2023-05-05 10:25 UTC, qcabrol commented on lang/cpp/src/Ubx.cpp
> +            writeByte(getDataStartAddress()[i], buf, index);
how are we sure of the bytes oendianness order in the buffer ? This is handled lower ?

2023-05-05 10:25 UTC, qcabrol commented on lang/cpp/src/parseUbxMessage.hpp
> +    class ParseUbxMessage : public ParseUbxMessageBase
comment headeer

2023-05-05 10:25 UTC, qcabrol commented on lang/cpp/src/parseUbxMessageBase.cpp
> +int32_t ParseUbxMessageBase::findUbxMessageStartIdx(const uint8_t *buf, uint16_t len) const
prototypes with header documentation missing

2023-05-05 10:25 UTC, qcabrol commented on ubx/Types.py
> +            s = bitfield[b]["s"]
better va r names ?

2023-05-05 10:25 UTC, qcabrol commented on ubx/Types.py
> +    """Variable-length array of unsigned chars.."""
stray point change

2023-05-05 10:25 UTC, qcabrol commented on ubx/Types.py
> +            s = bitfield[b]["s"]
to mention one is the bitshift and the other a byteshift ? That or a minor comment

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +def getBitName(field,  bit):
small comment doc for each routine

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +def getBitNameUp(field, bit):
getBitNameUpperCase() 
would be more transparent as a name

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +                file.write(f"        enum _{name}{field[0]}_allowed{{\n")
why the spaces after "  f"  " ? Identation purpose ?

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    if fields:
missing comment for the routine

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    if fields:
Generate bitfield allowed values as C enums from the corresponding py classes allowed dict fields.

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +                    key = allowed[a].replace(' ', '_').replace('-', '_')
Should we conside other special separators like "." here ? (apparently none of the allowed fields use the . at the moment)

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +"""Generate CPP code from the UBX message definitions in UBX/."""
missing readme for the updated gen script ?

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    messageName = getMessageName(
where is getMessageName() defined ?

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    fields = getClassMembers(Message.Fields)
where is  getClassMembers() defined ?

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    fields = getClassMembers(Message.Fields)
ubx/introspect.py:51:def getClassMembers(cls, predicate=None):

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
> +    messageName = getMessageName(
nevermind, found on introspect.py

2023-05-05 10:25 UTC, qcabrol commented on ubx/generateCPP.py
>              __version__,
do we want to update the version number as you did major changes ?

2023-05-09 11:17 UTC, Hadatko commented on ubx/generateCPP.py
> +                file.write(f"        enum _{name}{field[0]}_allowed{{\n")
yes

2023-05-09 11:21 UTC, Hadatko commented on ubx/generateCPP.py
> +                    key = allowed[a].replace(' ', '_').replace('-', '_')
Can be added once needed, but currently they are not.

2023-05-09 11:52 UTC, Hadatko commented on ubx/generateCPP.py
>              __version__,
yes we can

2023-05-09 13:26 UTC, Hadatko commented on lang/cpp/src/Ubx.cpp
> +            writeByte(getDataStartAddress()[i], buf, index);
No it was prototyped as LE

2023-05-10 12:02 UTC, qcabrol approved these changes
Changes on documentation and fix on packet size calculation have landed. Happy with the current PR I think we can move forward

2023-05-10 12:06 UTC, merged